apiVersion: v1
kind: Secret
metadata:
  name: glue-s3-creds
  namespace: {your-ocp-project}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {printf $REAL_AWS_ACCESS_KEY_ID | base64 -w 0}
  AWS_SECRET_ACCESS_KEY: {printf $REAL_AWS_SECRET_ACCESS_KEY | base64 -w 0}
stringData:
  ENDPOINT_URL: {REAL_ENDPOINT_URL}
